[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "hastycompute"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
    "numpy",
    "torch",
]

[tool.setuptools.packages.find]
where = ["."]
